### ISSUE TITLE
Add paper reference to README.md

### ISSUE THREAD

**Issue by tobigithub** [lfnothias/Combinatorial_BileAcids_DB_COSMIC#1]
High-confidence structural annotation of metabolites absent from spectral libraries
[Martin A. Hoffmann](https://www.nature.com/articles/s41587-021-01045-9#auth-Martin_A_-Hoffmann), [Louis-Félix Nothias](https://www.nature.com/articles/s41587-021-01045-9#auth-Louis_F_lix-Nothias), [Marcus Ludwig](https://www.nature.com/articles/s41587-021-01045-9#auth-Marcus-Ludwig), [Markus Fleischauer](https://www.nature.com/articles/s41587-021-01045-9#auth-Markus-Fleischauer), [Emily C. Gentry](https://www.nature.com/articles/s41587-021-01045-9#auth-Emily_C_-Gentry), [Michael Witting](https://www.nature.com/articles/s41587-021-01045-9#auth-Michael-Witting), [Pieter C. Dorrestein](https://www.nature.com/articles/s41587-021-01045-9#auth-Pieter_C_-Dorrestein), [Kai Dührkop](https://www.nature.com/articles/s41587-021-01045-9#auth-Kai-D_hrkop) & [Sebastian Böcker](https://www.nature.com/articles/s41587-021-01045-9#auth-Sebastian-B_cker); [Nature Biotechnology](https://www.nature.com/nbt) volume 40, pages411–421 (2022)[Cite this article](https://www.nature.com/articles/s41587-021-01045-9#citeas)

https://www.nature.com/articles/s41587-021-01045-9

**Comment by lfnothias** [comment]
Thanks ! :)
